
FIXTURES = [
  {:away=>"Atlanta Falcons", :home=>"Philadelphia Eagles"},
  {:away=>"Buffalo Bills", :home=>"Baltimore Ravens"},
  {:away=>"Cincinnati Bengals", :home=>"Indianapolis Colts"},
  {:away=>"Houston Texans", :home=>"New England Patriots"},
  {:away=>"Jacksonville Jaguars", :home=>"New York Giants"},
  {:away=>"Pittsburgh Steelers", :home=>"Cleveland Browns"},
  {:away=>"San Francisco 49ers", :home=>"Minnesota Vikings"},
  {:away=>"Tampa Bay Buccaneers", :home=>"New Orleans Saints"},
  {:away=>"Tennessee Titans", :home=>"Miami Dolphins"},
  {:away=>"Kansas City Chiefs", :home=>"Los Angeles Chargers"},
  {:away=>"Dallas Cowboys", :home=>"Carolina Panthers"},
  {:away=>"Seattle Seahawks", :home=>"Denver Broncos"},
  {:away=>"Washington Redskins", :home=>"Arizona Cardinals"},
  {:away=>"Chicago Bears", :home=>"Green Bay Packers"},
  {:away=>"New York Jets", :home=>"Detroit Lions"},
  {:away=>"Los Angeles Rams", :home=>"Oakland Raiders"},
  {:away=>"Baltimore Ravens", :home=>"Cincinnati Bengals"},
  {:away=>"Carolina Panthers", :home=>"Atlanta Falcons"},
  {:away=>"Cleveland Browns", :home=>"New Orleans Saints"},
  {:away=>"Houston Texans", :home=>"Tennessee Titans"},
  {:away=>"Indianapolis Colts", :home=>"Washington Redskins"},
  {:away=>"Kansas City Chiefs", :home=>"Pittsburgh Steelers"},
  {:away=>"Los Angeles Chargers", :home=>"Buffalo Bills"},
  {:away=>"Miami Dolphins", :home=>"New York Jets"},
  {:away=>"Minnesota Vikings", :home=>"Green Bay Packers"},
  {:away=>"Philadelphia Eagles", :home=>"Tampa Bay Buccaneers"},
  {:away=>"Arizona Cardinals", :home=>"Los Angeles Rams"},
  {:away=>"Detroit Lions", :home=>"San Francisco 49ers"},
  {:away=>"New England Patriots", :home=>"Jacksonville Jaguars"},
  {:away=>"Oakland Raiders", :home=>"Denver Broncos"},
  {:away=>"New York Giants", :home=>"Dallas Cowboys"},
  {:away=>"Seattle Seahawks", :home=>"Chicago Bears"},
  {:away=>"New York Jets", :home=>"Cleveland Browns"},
  {:away=>"Buffalo Bills", :home=>"Minnesota Vikings"},
  {:away=>"Cincinnati Bengals", :home=>"Carolina Panthers"},
  {:away=>"Denver Broncos", :home=>"Baltimore Ravens"},
  {:away=>"Green Bay Packers", :home=>"Washington Redskins"},
  {:away=>"Indianapolis Colts", :home=>"Philadelphia Eagles"},
  {:away=>"New Orleans Saints", :home=>"Atlanta Falcons"},
  {:away=>"New York Giants", :home=>"Houston Texans"},
  {:away=>"Oakland Raiders", :home=>"Miami Dolphins"},
  {:away=>"San Francisco 49ers", :home=>"Kansas City Chiefs"},
  {:away=>"Tennessee Titans", :home=>"Jacksonville Jaguars"},
  {:away=>"Los Angeles Chargers", :home=>"Los Angeles Rams"},
  {:away=>"Chicago Bears", :home=>"Arizona Cardinals"},
  {:away=>"Dallas Cowboys", :home=>"Seattle Seahawks"},
  {:away=>"New England Patriots", :home=>"Detroit Lions"},
  {:away=>"Pittsburgh Steelers", :home=>"Tampa Bay Buccaneers"},
  {:away=>"Minnesota Vikings", :home=>"Los Angeles Rams"},
  {:away=>"Buffalo Bills", :home=>"Green Bay Packers"},
  {:away=>"Cincinnati Bengals", :home=>"Atlanta Falcons"},
  {:away=>"Detroit Lions", :home=>"Dallas Cowboys"},
  {:away=>"Houston Texans", :home=>"Indianapolis Colts"},
  {:away=>"Miami Dolphins", :home=>"New England Patriots"},
  {:away=>"New York Jets", :home=>"Jacksonville Jaguars"},
  {:away=>"Philadelphia Eagles", :home=>"Tennessee Titans"},
  {:away=>"Tampa Bay Buccaneers", :home=>"Chicago Bears"},
  {:away=>"Cleveland Browns", :home=>"Oakland Raiders"},
  {:away=>"Seattle Seahawks", :home=>"Arizona Cardinals"},
  {:away=>"New Orleans Saints", :home=>"New York Giants"},
  {:away=>"San Francisco 49ers", :home=>"Los Angeles Chargers"},
  {:away=>"Baltimore Ravens", :home=>"Pittsburgh Steelers"},
  {:away=>"Kansas City Chiefs", :home=>"Denver Broncos"},
  {:away=>"Indianapolis Colts", :home=>"New England Patriots"},
  {:away=>"Atlanta Falcons", :home=>"Pittsburgh Steelers"},
  {:away=>"Baltimore Ravens", :home=>"Cleveland Browns"},
  {:away=>"Denver Broncos", :home=>"New York Jets"},
  {:away=>"Green Bay Packers", :home=>"Detroit Lions"},
  {:away=>"Jacksonville Jaguars", :home=>"Kansas City Chiefs"},
  {:away=>"Miami Dolphins", :home=>"Cincinnati Bengals"},
  {:away=>"New York Giants", :home=>"Carolina Panthers"},
  {:away=>"Tennessee Titans", :home=>"Buffalo Bills"},
  {:away=>"Oakland Raiders", :home=>"Los Angeles Chargers"},
  {:away=>"Arizona Cardinals", :home=>"San Francisco 49ers"},
  {:away=>"Los Angeles Rams", :home=>"Seattle Seahawks"},
  {:away=>"Minnesota Vikings", :home=>"Philadelphia Eagles"},
  {:away=>"Dallas Cowboys", :home=>"Houston Texans"},
  {:away=>"Washington Redskins", :home=>"New Orleans Saints"},
  {:away=>"Philadelphia Eagles", :home=>"New York Giants"},
  {:away=>"Arizona Cardinals", :home=>"Minnesota Vikings"},
  {:away=>"Buffalo Bills", :home=>"Houston Texans"},
  {:away=>"Carolina Panthers", :home=>"Washington Redskins"},
  {:away=>"Chicago Bears", :home=>"Miami Dolphins"},
  {:away=>"Indianapolis Colts", :home=>"New York Jets"},
  {:away=>"Los Angeles Chargers", :home=>"Cleveland Browns"},
  {:away=>"Pittsburgh Steelers", :home=>"Cincinnati Bengals"},
  {:away=>"Seattle Seahawks", :home=>"Oakland Raiders"},
  {:away=>"Tampa Bay Buccaneers", :home=>"Atlanta Falcons"},
  {:away=>"Los Angeles Rams", :home=>"Denver Broncos"},
  {:away=>"Baltimore Ravens", :home=>"Tennessee Titans"},
  {:away=>"Jacksonville Jaguars", :home=>"Dallas Cowboys"},
  {:away=>"Kansas City Chiefs", :home=>"New England Patriots"},
  {:away=>"San Francisco 49ers", :home=>"Green Bay Packers"},
  {:away=>"Denver Broncos", :home=>"Arizona Cardinals"},
  {:away=>"Tennessee Titans", :home=>"Los Angeles Chargers"},
  {:away=>"Buffalo Bills", :home=>"Indianapolis Colts"},
  {:away=>"Carolina Panthers", :home=>"Philadelphia Eagles"},
  {:away=>"Cincinnati Bengals", :home=>"Kansas City Chiefs"},
  {:away=>"Cleveland Browns", :home=>"Tampa Bay Buccaneers"},
  {:away=>"Detroit Lions", :home=>"Miami Dolphins"},
  {:away=>"Houston Texans", :home=>"Jacksonville Jaguars"},
  {:away=>"Minnesota Vikings", :home=>"New York Jets"},
  {:away=>"New England Patriots", :home=>"Chicago Bears"},
  {:away=>"New Orleans Saints", :home=>"Baltimore Ravens"},
  {:away=>"Dallas Cowboys", :home=>"Washington Redskins"},
  {:away=>"Los Angeles Rams", :home=>"San Francisco 49ers"},
  {:away=>"New York Giants", :home=>"Atlanta Falcons"},
  {:away=>"Miami Dolphins", :home=>"Houston Texans"},
  {:away=>"Philadelphia Eagles", :home=>"Jacksonville Jaguars"},
  {:away=>"Baltimore Ravens", :home=>"Carolina Panthers"},
  {:away=>"Cleveland Browns", :home=>"Pittsburgh Steelers"},
  {:away=>"Denver Broncos", :home=>"Kansas City Chiefs"},
  {:away=>"New York Jets", :home=>"Chicago Bears"},
  {:away=>"Seattle Seahawks", :home=>"Detroit Lions"},
  {:away=>"Tampa Bay Buccaneers", :home=>"Cincinnati Bengals"},
  {:away=>"Washington Redskins", :home=>"New York Giants"},
  {:away=>"Indianapolis Colts", :home=>"Oakland Raiders"},
  {:away=>"Green Bay Packers", :home=>"Los Angeles Rams"},
  {:away=>"San Francisco 49ers", :home=>"Arizona Cardinals"},
  {:away=>"New Orleans Saints", :home=>"Minnesota Vikings"},
  {:away=>"New England Patriots", :home=>"Buffalo Bills"},
  {:away=>"Oakland Raiders", :home=>"San Francisco 49ers"},
  {:away=>"Atlanta Falcons", :home=>"Washington Redskins"},
  {:away=>"Chicago Bears", :home=>"Buffalo Bills"},
  {:away=>"Detroit Lions", :home=>"Minnesota Vikings"},
  {:away=>"Kansas City Chiefs", :home=>"Cleveland Browns"},
  {:away=>"New York Jets", :home=>"Miami Dolphins"},
  {:away=>"Pittsburgh Steelers", :home=>"Baltimore Ravens"},
  {:away=>"Tampa Bay Buccaneers", :home=>"Carolina Panthers"},
  {:away=>"Houston Texans", :home=>"Denver Broncos"},
  {:away=>"Los Angeles Chargers", :home=>"Seattle Seahawks"},
  {:away=>"Los Angeles Rams", :home=>"New Orleans Saints"},
  {:away=>"Green Bay Packers", :home=>"New England Patriots"},
  {:away=>"Tennessee Titans", :home=>"Dallas Cowboys"},
  {:away=>"Carolina Panthers", :home=>"Pittsburgh Steelers"},
  {:away=>"Arizona Cardinals", :home=>"Kansas City Chiefs"},
  {:away=>"Atlanta Falcons", :home=>"Cleveland Browns"},
  {:away=>"Buffalo Bills", :home=>"New York Jets"},
  {:away=>"Detroit Lions", :home=>"Chicago Bears"},
  {:away=>"Jacksonville Jaguars", :home=>"Indianapolis Colts"},
  {:away=>"Miami Dolphins", :home=>"Green Bay Packers"},
  {:away=>"New England Patriots", :home=>"Tennessee Titans"},
  {:away=>"New Orleans Saints", :home=>"Cincinnati Bengals"},
  {:away=>"Washington Redskins", :home=>"Tampa Bay Buccaneers"},
  {:away=>"Los Angeles Chargers", :home=>"Oakland Raiders"},
  {:away=>"Seattle Seahawks", :home=>"Los Angeles Rams"},
  {:away=>"Dallas Cowboys", :home=>"Philadelphia Eagles"},
  {:away=>"New York Giants", :home=>"San Francisco 49ers"},
  {:away=>"Green Bay Packers", :home=>"Seattle Seahawks"},
  {:away=>"Carolina Panthers", :home=>"Detroit Lions"},
  {:away=>"Cincinnati Bengals", :home=>"Baltimore Ravens"},
  {:away=>"Dallas Cowboys", :home=>"Atlanta Falcons"},
  {:away=>"Houston Texans", :home=>"Washington Redskins"},
  {:away=>"Minnesota Vikings", :home=>"Chicago Bears"},
  {:away=>"Philadelphia Eagles", :home=>"New Orleans Saints"},
  {:away=>"Tampa Bay Buccaneers", :home=>"New York Giants"},
  {:away=>"Tennessee Titans", :home=>"Indianapolis Colts"},
  {:away=>"Denver Broncos", :home=>"Los Angeles Chargers"},
  {:away=>"Oakland Raiders", :home=>"Arizona Cardinals"},
  {:away=>"Pittsburgh Steelers", :home=>"Jacksonville Jaguars"},
  {:away=>"Kansas City Chiefs", :home=>"Los Angeles Rams"},
  {:away=>"Chicago Bears", :home=>"Detroit Lions"},
  {:away=>"Washington Redskins", :home=>"Dallas Cowboys"},
  {:away=>"Atlanta Falcons", :home=>"New Orleans Saints"},
  {:away=>"Cleveland Browns", :home=>"Cincinnati Bengals"},
  {:away=>"Jacksonville Jaguars", :home=>"Buffalo Bills"},
  {:away=>"Miami Dolphins", :home=>"Indianapolis Colts"},
  {:away=>"New England Patriots", :home=>"New York Jets"},
  {:away=>"New York Giants", :home=>"Philadelphia Eagles"},
  {:away=>"Oakland Raiders", :home=>"Baltimore Ravens"},
  {:away=>"San Francisco 49ers", :home=>"Tampa Bay Buccaneers"},
  {:away=>"Seattle Seahawks", :home=>"Carolina Panthers"},
  {:away=>"Arizona Cardinals", :home=>"Los Angeles Chargers"},
  {:away=>"Pittsburgh Steelers", :home=>"Denver Broncos"},
  {:away=>"Green Bay Packers", :home=>"Minnesota Vikings"},
  {:away=>"Tennessee Titans", :home=>"Houston Texans"},
  {:away=>"New Orleans Saints", :home=>"Dallas Cowboys"},
  {:away=>"Arizona Cardinals", :home=>"Green Bay Packers"},
  {:away=>"Baltimore Ravens", :home=>"Atlanta Falcons"},
  {:away=>"Buffalo Bills", :home=>"Miami Dolphins"},
  {:away=>"Carolina Panthers", :home=>"Tampa Bay Buccaneers"},
  {:away=>"Chicago Bears", :home=>"New York Giants"},
  {:away=>"Cleveland Browns", :home=>"Houston Texans"},
  {:away=>"Denver Broncos", :home=>"Cincinnati Bengals"},
  {:away=>"Indianapolis Colts", :home=>"Jacksonville Jaguars"},
  {:away=>"Los Angeles Chargers", :home=>"Pittsburgh Steelers"},
  {:away=>"Los Angeles Rams", :home=>"Detroit Lions"},
  {:away=>"Kansas City Chiefs", :home=>"Oakland Raiders"},
  {:away=>"New York Jets", :home=>"Tennessee Titans"},
  {:away=>"Minnesota Vikings", :home=>"New England Patriots"},
  {:away=>"San Francisco 49ers", :home=>"Seattle Seahawks"},
  {:away=>"Washington Redskins", :home=>"Philadelphia Eagles"},
  {:away=>"Jacksonville Jaguars", :home=>"Tennessee Titans"},
  {:away=>"Atlanta Falcons", :home=>"Green Bay Packers"},
  {:away=>"Baltimore Ravens", :home=>"Kansas City Chiefs"},
  {:away=>"Carolina Panthers", :home=>"Cleveland Browns"},
  {:away=>"Indianapolis Colts", :home=>"Houston Texans"},
  {:away=>"Los Angeles Rams", :home=>"Chicago Bears"},
  {:away=>"New England Patriots", :home=>"Miami Dolphins"},
  {:away=>"New Orleans Saints", :home=>"Tampa Bay Buccaneers"},
  {:away=>"New York Giants", :home=>"Washington Redskins"},
  {:away=>"New York Jets", :home=>"Buffalo Bills"},
  {:away=>"Cincinnati Bengals", :home=>"Los Angeles Chargers"},
  {:away=>"Denver Broncos", :home=>"San Francisco 49ers"},
  {:away=>"Detroit Lions", :home=>"Arizona Cardinals"},
  {:away=>"Philadelphia Eagles", :home=>"Dallas Cowboys"},
  {:away=>"Pittsburgh Steelers", :home=>"Oakland Raiders"},
  {:away=>"Minnesota Vikings", :home=>"Seattle Seahawks"},
  {:away=>"Los Angeles Chargers", :home=>"Kansas City Chiefs"},
  {:away=>"Cleveland Browns", :home=>"Denver Broncos"},
  {:away=>"Houston Texans", :home=>"New York Jets"},
  {:away=>"Arizona Cardinals", :home=>"Atlanta Falcons"},
  {:away=>"Dallas Cowboys", :home=>"Indianapolis Colts"},
  {:away=>"Detroit Lions", :home=>"Buffalo Bills"},
  {:away=>"Green Bay Packers", :home=>"Chicago Bears"},
  {:away=>"Miami Dolphins", :home=>"Minnesota Vikings"},
  {:away=>"Oakland Raiders", :home=>"Cincinnati Bengals"},
  {:away=>"Tampa Bay Buccaneers", :home=>"Baltimore Ravens"},
  {:away=>"Tennessee Titans", :home=>"New York Giants"},
  {:away=>"Washington Redskins", :home=>"Jacksonville Jaguars"},
  {:away=>"Seattle Seahawks", :home=>"San Francisco 49ers"},
  {:away=>"New England Patriots", :home=>"Pittsburgh Steelers"},
  {:away=>"Philadelphia Eagles", :home=>"Los Angeles Rams"},
  {:away=>"New Orleans Saints", :home=>"Carolina Panthers"},
  {:away=>"Atlanta Falcons", :home=>"Carolina Panthers"},
  {:away=>"Buffalo Bills", :home=>"New England Patriots"},
  {:away=>"Cincinnati Bengals", :home=>"Cleveland Browns"},
  {:away=>"Green Bay Packers", :home=>"New York Jets"},
  {:away=>"Houston Texans", :home=>"Philadelphia Eagles"},
  {:away=>"Jacksonville Jaguars", :home=>"Miami Dolphins"},
  {:away=>"Minnesota Vikings", :home=>"Detroit Lions"},
  {:away=>"New York Giants", :home=>"Indianapolis Colts"},
  {:away=>"Tampa Bay Buccaneers", :home=>"Dallas Cowboys"},
  {:away=>"Washington Redskins", :home=>"Tennessee Titans"},
  {:away=>"Baltimore Ravens", :home=>"Los Angeles Chargers"},
  {:away=>"Chicago Bears", :home=>"San Francisco 49ers"},
  {:away=>"Los Angeles Rams", :home=>"Arizona Cardinals"},
  {:away=>"Pittsburgh Steelers", :home=>"New Orleans Saints"},
  {:away=>"Kansas City Chiefs", :home=>"Seattle Seahawks"},
  {:away=>"Denver Broncos", :home=>"Oakland Raiders"},
  {:away=>"Atlanta Falcons", :home=>"Tampa Bay Buccaneers"},
  {:away=>"Carolina Panthers", :home=>"New Orleans Saints"},
  {:away=>"Chicago Bears", :home=>"Minnesota Vikings"},
  {:away=>"Cincinnati Bengals", :home=>"Pittsburgh Steelers"},
  {:away=>"Cleveland Browns", :home=>"Baltimore Ravens"},
  {:away=>"Dallas Cowboys", :home=>"New York Giants"},
  {:away=>"Detroit Lions", :home=>"Green Bay Packers"},
  {:away=>"Indianapolis Colts", :home=>"Tennessee Titans"},
  {:away=>"Jacksonville Jaguars", :home=>"Houston Texans"},
  {:away=>"Miami Dolphins", :home=>"Buffalo Bills"},
  {:away=>"New York Jets", :home=>"New England Patriots"},
  {:away=>"Oakland Raiders", :home=>"Kansas City Chiefs"},
  {:away=>"Philadelphia Eagles", :home=>"Washington Redskins"},
  {:away=>"Arizona Cardinals", :home=>"Seattle Seahawks"},
  {:away=>"Los Angeles Chargers", :home=>"Denver Broncos"},
  {:away=>"San Francisco 49ers", :home=>"Los Angeles Rams"}
]
